
---        
apiVersion: v1
kind: Service
metadata:
  name: my-nginx0-svc
  labels:
    app: nginx0
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx0
  labels:
    app: nginx0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx0
  template:
    metadata:
      labels:
        app: nginx0
    spec:
      containers:
      - name: nginx0
        image: nginx:1.14.2
        ports:
        - containerPort: 80        

---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx1-svc
  labels:
    app: nginx1
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx1
  labels:
    app: nginx1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx1
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---        
apiVersion: v1
kind: Service
metadata:
  name: my-nginx2-svc
  labels:
    app: nginx2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx2
  labels:
    app: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx2
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---        
apiVersion: v1
kind: Service
metadata:
  name: my-nginx3-svc
  labels:
    app: nginx3
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx3
  labels:
    app: nginx3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx3
  template:
    metadata:
      labels:
        app: nginx3
    spec:
      containers:
      - name: nginx3
        image: nginx:1.14.2
        ports:
        - containerPort: 80        